services:
  app:
    build: .
    container_name: react-ubuntu-test
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    ports:
      - "5173:5173" # Viteのデフォルトポート
    command: npm run dev -- --host
    